import json
from markdown import markdown as md_convert
from pathlib import Path
import logging

logger = logging.getLogger(__name__)

class DocumentationGenerator:
    def __init__(self, output_dir: str = "./data/outputs"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_dev_docs_markdown(self, file_tree: str, code_structure: dict, analysis: dict) -> str:
        """Generate developer documentation in Markdown."""
        return f"""# Developer Documentation

## Project Structure
```
{file_tree}
```

## Module Overview

### Key Modules
{json.dumps(analysis.get('key_modules', []), indent=2)}

### Dependencies
{json.dumps(analysis.get('dependencies', []), indent=2)}

## Architecture
{analysis.get('architecture', 'No architecture analysis available')}

## Code Structure

### Imports & Dependencies
```
{json.dumps(code_structure.get('imports', [])[:10], indent=2)}
```

### Functions & Methods
```
{json.dumps(code_structure.get('functions', [])[:20], indent=2)}
```

### Classes & Types
```
{json.dumps(code_structure.get('classes', [])[:10], indent=2)}
```

## Patterns & Conventions
{json.dumps(analysis.get('patterns', []), indent=2)}

---
Generated by Codebase Documentor
"""

    def generate_user_guide_markdown(self, analysis: dict) -> str:
        """Generate user-friendly guide."""
        return f"""# User Guide

## Quick Start

This project provides the following core functionality:

### Main Components
{json.dumps(analysis.get('key_modules', []), indent=2)}

## Installation & Setup

1. Clone the repository
2. Install dependencies
3. Configure environment
4. Run the application

## Features

The following features are available:
- Core functionality
- Integration capabilities
- API/library usage

## FAQ

**Q: How do I configure this?**
A: Refer to the Developer Documentation for configuration details.

## Support

For issues and questions, refer to the project repository.

---
Generated by Codebase Documentor
"""

    def markdown_to_html(self, markdown_content: str, title: str = "Documentation") -> str:
        """Convert Markdown to styled HTML."""
        try:
            html_body = md_convert(markdown_content, extensions=['fenced_code', 'toc'])
        except Exception as e:
            logger.warning(f"Markdown conversion failed: {e}")
            html_body = md_convert(markdown_content)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ 
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #f5f5f5;
        }}
        .container {{ max-width: 1000px; margin: 0 auto; background: white; padding: 40px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }}
        h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; margin: 30px 0 20px; }}
        h2 {{ color: #34495e; margin: 25px 0 15px; }}
        h3 {{ color: #7f8c8d; margin: 20px 0 10px; }}
        code {{ 
            background: #f4f4f4; 
            padding: 2px 6px; 
            border-radius: 3px;
            font-family: 'Courier New', monospace;
            font-size: 14px;
        }}
        pre {{ 
            background: #2c3e50; 
            color: #ecf0f1; 
            padding: 15px; 
            border-radius: 5px;
            overflow-x: auto;
            margin: 15px 0;
            line-height: 1.4;
        }}
        pre code {{ background: none; padding: 0; color: inherit; }}
        a {{ color: #3498db; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        blockquote {{ border-left: 4px solid #3498db; padding-left: 15px; margin: 15px 0; color: #666; }}
        table {{ border-collapse: collapse; width: 100%; margin: 15px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
        th {{ background: #f4f4f4; font-weight: bold; }}
    </style>
</head>
<body>
    <div class="container">
        {html_body}
    </div>
</body>
</html>"""

    def save_documentation(self, repo_name: str, dev_docs: str, user_docs: str, metadata: dict):
        """Save all documentation files."""
        repo_dir = self.output_dir / repo_name
        repo_dir.mkdir(parents=True, exist_ok=True)

        # Save Markdown
        (repo_dir / "DEVELOPER_DOCS.md").write_text(dev_docs)
        (repo_dir / "USER_GUIDE.md").write_text(user_docs)

        # Save HTML
        dev_html = self.markdown_to_html(dev_docs, "Developer Documentation")
        user_html = self.markdown_to_html(user_docs, "User Guide")

        (repo_dir / "DEVELOPER_DOCS.html").write_text(dev_html)
        (repo_dir / "USER_GUIDE.html").write_text(user_html)

        # Save metadata
        (repo_dir / "metadata.json").write_text(json.dumps(metadata, indent=2))

        logger.info(f"Documentation saved to {repo_dir}")
        return repo_dir
